# Site settings
title:          After Shift
description:    "After Shift is a open source community which is created by open source lovers to develop and maintain open source projects."
baseurl:        "/aftershift"
url:            "https://gormelof.github.io"

# Google Analytics
#google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Ömer Faruk Görmel
  url:          https://gormelof.github.io
  email:        gormelomerfaruk@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
